### ISSUE TITLE
pre-commit报错，cargo-deny有deprecated warning和error

### ISSUE THREAD

**Issue by m104ngc4594** [tyr-rust-bootcamp/template#2]
warning和报错提示：
warning[deprecated]: this key will be removed in a future update, see https://github.com/EmbarkStudios/cargo-deny/pull/611 for details
   ┌─ /home/ptxc/rcli/deny.toml:39:1
   │
39 │ vulnerability = "deny"
   │ ^^^^^^^^^^^^^

warning[deprecated]: this key will be removed in a future update, see https://github.com/EmbarkStudios/cargo-deny/pull/611 for details
   ┌─ /home/ptxc/rcli/deny.toml:41:1
   │
41 │ unmaintained = "warn"
   │ ^^^^^^^^^^^^

warning[deprecated]: this key will be removed in a future update, see https://github.com/EmbarkStudios/cargo-deny/pull/611 for details
   ┌─ /home/ptxc/rcli/deny.toml:47:1
   │
47 │ notice = "warn"
   │ ^^^^^^

warning[deprecated]: this key will be removed in a future update, see https://github.com/EmbarkStudios/cargo-deny/pull/611 for details
   ┌─ /home/ptxc/rcli/deny.toml:68:1
   │
68 │ unlicensed = "allow"
   │ ^^^^^^^^^^

warning[deprecated]: this key will be removed in a future update, see https://github.com/EmbarkStudios/cargo-deny/pull/611 for details
   ┌─ /home/ptxc/rcli/deny.toml:96:1
   │
96 │ allow-osi-fsf-free = "neither"
   │ ^^^^^^^^^^^^^^^^^^

warning[deprecated]: this key will be removed in a future update, see https://github.com/EmbarkStudios/cargo-deny/pull/611 for details
   ┌─ /home/ptxc/rcli/deny.toml:89:1
   │
89 │ copyleft = "warn"
   │ ^^^^^^^^

warning[deprecated]: this key will be removed in a future update, see https://github.com/EmbarkStudios/cargo-deny/pull/611 for details
    ┌─ /home/ptxc/rcli/deny.toml:101:1
    │
101 │ default = "deny"
    │ ^^^^^^^

warning[deprecated]: this key will be removed in a future update, see https://github.com/EmbarkStudios/cargo-deny/pull/611 for details
   ┌─ /home/ptxc/rcli/deny.toml:85:1
   │
85 │ deny = [
   │ ^^^^

warning[deprecated]: this key has been moved to [graph]
   ┌─ /home/ptxc/rcli/deny.toml:20:1
   │
20 │ targets = [
   │ ^^^^^^^

2024-04-16 02:09:55 [ERROR] failed to open advisory database: "/home/ptxc/.cargo/advisory-db/github.com-2f857891b7f43c59" does not appear to be a git repository: Could not retrieve metadata of "/home/ptxc/.cargo/advisory-db/github.com-2f857891b7f43c59": No such file or directory (os error 2)

像这样的情况应该按提示修改warning吗？另外，报错应该怎么修复？

**Comment by ccsunnyfd** [comment]
1. 安装cargo-deny的时候加上--locked参数：cargo install cargo-deny --locked
2. cargo-deny init生成当前版本的配置文件deny.toml
3. [licenses]下粘贴如下：
```
unlicensed` = "allow"
allow = [
    "MIT",
    "Apache-2.0",
    "Unicode-DFS-2016",
    "MPL-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "CC0-1.0",
]
```

**Comment by taoztw** [comment]
已复现，解决办法:
```bash
rm -rf ~/.cargo/advisory-db
cargo install  cargo-audit
cargo audit

cargo deny init
# 生成 deny.toml文件。将如下配置防止toml合适位置
```
修改deny.toml
```toml
unlicensed = "allow"
allow = [
    "MIT",
    "Apache-2.0",
    "Unicode-DFS-2016",
    "MPL-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "CC0-1.0",
]
```

**Comment by m104ngc4594** [comment]
除了以上操作外，我运行了cargo deny check，以后就可以不再有error了

**Comment by dnxxymcj** [comment]
error[deprecated]: this key has been removed, see https://github.com/EmbarkStudios/cargo-deny/pull/611 for migration information
   ┌─ /Users/cj/workspace/rusty/rcli/deny.toml:91:1
   │
91 │ unlicensed = "allow"
   │ ━━━━━━━━━━

2024-11-09 06:20:10 [ERROR] failed to validate configuration file /Users/cj/workspace/rusty/rcli/deny.toml

我这还报这错，怎么弄啊
